### ISSUE TITLE
Flickr OATH or browser require https?

### ISSUE THREAD

**Issue by BeastOfBodmin** [marchaos/flickr_retriever#3]
$ node index.js 
Cache file for key oath does not exist
No credentials file, so login
Open your browser to http://localhost:3000

So I open http://localhost:3000 and

![Screenshot 2022-06-07 at 08 52 25](https://user-images.githubusercontent.com/3684836/172315147-464c66dd-e835-4939-988a-6d2ea17681d6.png)

Click "OK I'LL AUTHORIZE" and

![Screenshot 2022-06-07 at 08 54 11](https://user-images.githubusercontent.com/3684836/172315319-9f6be7f4-eff2-4b9d-be87-91d0e3a9c64b.png)

Using Brave, I get a similar result (though less easy to understand).

As far as I can tell, nothing is downloading.

**Comment by marchaos** [comment]
should be fixed now.
